name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_doc:
    name: 'Build cpython doc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: clone docsbuild scripts
        run: |
          git clone https://github.com/python/docsbuild-scripts/
      - name: setup requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install jinja2 markupsafe
      - name: build docs
        run: |
          python3 ./docsbuild-scripts/build_docs.py --quick --build-root ./build_root --www-root ./www --log-directory ./logs --group $(id -g) --skip-cache-invalidation --theme $(pwd) --language en --branch 3.9
      - name: 'Upload'
        uses: actions/upload-artifact@v2.2.2
        with:
          name: doc-html
          path: www/
