name: Tests

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  build_doc:
    name: Build CPython docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ["origin/main", "3.12", "3.11", "3.10", "3.9", "3.8"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3
          allow-prereleases: true
          cache: pip
      - name: Clone docsbuild scripts
        run: |
          git clone https://github.com/python/docsbuild-scripts/
      - name: Set up requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docsbuild-scripts/requirements.txt
      - name: Build documentation
        run: >
          python ./docsbuild-scripts/build_docs.py
          --quick
          --build-root ./build_root
          --www-root ./www
          --log-directory ./logs
          --group $(id -g)
          --skip-cache-invalidation
          --theme $(pwd)
          --language en
          --branch ${{ matrix.branch }}
      - name: Show logs
        if: failure()
        run: |
          cat ./logs/docsbuild.log
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: doc-html-${{ matrix.branch }}
          path: www/
